### PR TITLE
Add zero width space after dangerous characters.

### PR DESCRIPTION
**Pull request by utkumaden**
Lazy bun.

### CODE REVIEW

**Review by Fl0GUI — CHANGES_REQUESTED** [review]
discordjs has support for this

**Comment by Fl0GUI** [comment]
> 

found it: https://discord.js.org/#/docs/main/stable/class/Util

**Comment by utkumaden** [comment]
It's deprecated.

**Comment by Fl0GUI** [comment]
well then just Use [BaseMessageOptions#allowedMentions](https://discord.js.org/#/docs/main/stable/typedef/BaseMessageOptions?scrollTo=allowedMentions) instead to prevent mentions when sending a message.

**Comment by utkumaden** [comment]
Closing for now, will update this later.

**Pull request closed without merging**
